# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- script: echo My Maven Application
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'Building the Maven application'

- script: mvn exec:java -Dexec.mainClass="com.example.App"
  displayName: 'Running the Maven application''
